### ISSUE TITLE
Design 

### ISSUE THREAD

**Issue by susikaltschmidt** [component-driven-workshop/project-group-five#1]
Task for designers:
Mobile first

Requirements for mobile:
- Icons have to be large enough (avoid fatty finger problem)
- Readable headline, sub headlines and text
- More contrast (light grey is not very good visible; especially for smartphone and different light atmospheres)

Design extensions:
- Background (colors, pattern or image)
- Different icons which are more understandable
- thin elegant lines

Interaction possibilites:
- Hover effects
- Color categorization

Further possibilities:
- Names for toDo lists
- Priority of tasks 
- More information on website (date, time)

**Comment by susikaltschmidt** [comment]
Mobile design questions:
- Which font size is best readable?
- Which icon size is best to be easy to touch but doesn´t take too much of space

**Comment by Katinkaa** [comment]
[ToDo.pdf](https://github.com/component-driven-workshop/project-group-five/files/621968/ToDo.pdf)

**Comment by kondkop** [comment]
![todos_1](https://cloud.githubusercontent.com/assets/24233639/20756880/a6706af2-b714-11e6-9c5f-f4974fbefbd9.png)

**Comment by kondkop** [comment]
![zeichenflache 3 kopie](https://cloud.githubusercontent.com/assets/24233639/20757902/56953e14-b718-11e6-9cc7-cf776baea423.png)

**Comment by susikaltschmidt** [comment]
Responsive UI versions (mobile, ipad, web)
![todo-responsive](https://cloud.githubusercontent.com/assets/24250406/20857402/50b22b32-b92b-11e6-9229-b62d926a40fb.jpg)

**Comment by kondkop** [comment]
![screen_ipad_landscape](https://cloud.githubusercontent.com/assets/24233639/20880954/5bbed998-bada-11e6-8f98-1706fab3858e.png)
![screen_ipad_portrait](https://cloud.githubusercontent.com/assets/24233639/20880955/5bc53284-bada-11e6-9a04-9b6d797189cf.png)
![screen_mobile](https://cloud.githubusercontent.com/assets/24233639/20880957/5bccceb8-bada-11e6-8cda-6d66e75d5aaf.png)
![screen_web](https://cloud.githubusercontent.com/assets/24233639/20880956/5bc530f4-bada-11e6-8450-9aa5fb3af07e.png)

**Comment by kondkop** [comment]
(mobile, ipad, web)

![screen_ipad_landscape](https://cloud.githubusercontent.com/assets/24233639/20880999/8b70a63a-bada-11e6-979e-ceb86452d2ba.png)
![screen_ipad_portrait](https://cloud.githubusercontent.com/assets/24233639/20881000/8b70c28c-bada-11e6-9997-bdd4a43e349d.png)
![screen_mobile](https://cloud.githubusercontent.com/assets/24233639/20881002/8b7198d8-bada-11e6-8bb2-c6f99b8bf0d3.png)
![screen_web](https://cloud.githubusercontent.com/assets/24233639/20881001/8b715116-bada-11e6-8758-0c699d6aaa09.png)

**Comment by susikaltschmidt** [comment]
Vom Aufbau sind beide ja an sich gleich. 
Schriftgröße und Farben können die Designer ja dann noch anpassen

**Comment by felixkittler** [comment]
Gute Vorarbeit, vielen Dank!
Von Development-Perspektive sind beide Entwürfe gleich gut geeignet.

Ich habe neulich schon die Ordner-Struktur im GIT entsprechend der Atom/Molekül/Organismus - Struktur geupdatet. Jetzt können wir mit Coden loslegen :-)

**Comment by kondkop** [comment]
grün oder grau? wirklich sinnstiftend ist ein farbiger hintergrund ja nicht. vom interface sind beide entwürfe ja eigentlich identisch.

**Comment by RadioSchattenwelt** [comment]
Also mit dem Grünton komm ich nicht so klar, das wirkt nicht wie ein fertiger Hintergrund, mehr wie ein Platzhalter

**Comment by felixkittler** [comment]
Ja, finde ich auch.
Entscheiden wir uns für Susi's ungrünen Entwurf? :-)

Struktureller Aufbau ist ja unabhängig von beidem, oder?`
Here's an overview of the elements, in order of appearance (top-down on site).
Atoms = [A] / Molecules = [M] / Organisms = [O] 

```
|- [A] globalHeader
|- [M] filterBar
   |- [A] filterButton
|- [A] addItemTextField
|- [A] counter
|- [O] taskList
   |- [M] listItem
      |- [A] icon
      |- [A] task
      |- [A] completeButton
```

**Comment by RadioSchattenwelt** [comment]
Ich finde auch, da es hauptsächlich um responsive geht, sollte dem ganzen in der Desktopansicht mehr breite gegeben werden

**Comment by felixkittler** [comment]
![2016-12-06 13_41_37-greenshot editor](https://cloud.githubusercontent.com/assets/18353984/20925879/be92281a-bbb9-11e6-834a-daec91231341.png)

This is Susie's Design with the components highlighted.
Note: A few components were slightly renamed.

**Comment by felixkittler** [comment]
@RadioSchattenwelt Nicole, kannst du die Ordner im GIT entsprechend umbenennen?

@all, ich denke damit ist eine Design-Entscheidung gefunden und dieser Issue geschlossen :-)
