### ISSUE TITLE
Dev

### ISSUE THREAD

**Issue by felixkittler** [component-driven-workshop/project-group-five#2]
Folder structure in ATOMS and MOLECULES has been adjusted as discussed.

Here's an overview of the elements, in order of appearance (top-down on site).
Atoms = [A] / Molecules = [M] / Organisms = [O] 

```
|- [A] globalHeader
|- [M] filterBar
   |- [A] filterButton
|- [A] addItemTextField
|- [A] counter
|- [O] taskList
   |- [M] listItem
      |- [A] icon
      |- [A] task
      |- [A] completeButton
```

**Comment by RadioSchattenwelt** [comment]
Adjusted names:

>`
|- [A] header
|- [M] filterBar
   |- [A] filterButton
|- [A] addItemTextField
|- [A] counter
|- [O] taskList
   |- [M] taskListItem
      |- [A] iconButton
      |- [A] taskTextField`

**Comment by felixkittler** [comment]
Added "template" as global parent element:

```
|- [T] todoMVC 
   |- [A] header
   |- [M] filterBar
      |- [A] filterButton
   |- [A] addItemTextField
   |- [A] counter
   |- [O] taskList
      |- [M] taskListItem
         |- [A] iconButton
         |- [A] taskTextField
```

**Comment by felixkittler** [comment]
Ich verwende folgende Farben:

Hintergrund #ededed
Dunkelgrau (z.B. Trennlinie unterm Header, Text-Farbe,...) #979797

Gibt es auch ein Hellgrau z.B. für den Platzhalter-Text im Input-Feld?

**Comment by felixkittler** [comment]
Leute, 

ich kriegs nich zum Laufen. Ich hab versucht die "input-bar" von Gruppe 6 zu klauen, bekomm sie aber nicht richtig verkabelt. Leider sagen einem die Fehlermeldungen auch nicht, in welcher Datei bzw. welchem Element der Fehler unsprünglich auftritt.

Ich pack's für heute und werde es nachher zu Hause nochmal (kurz) probieren.

**Comment by RadioSchattenwelt** [comment]
Ich hab noch ein bisschen was gepusht, vlt kannst dich ja anhand dessen um die filter Funktion kümmern?
Die onFilterChanged methode funktioniert auf jeden Fall schon ;-)
Hab auch schon etwas am TaskListItem gearbeitet, da gibt es schon eine onCheckButtonClicked und eine onDeleteButtonClicked.

Dann versuch ich mich vlt mal an der input Zeile
