### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by susikaltschmidt** [component-driven-workshop/project-group-five#3]
Please document all your experiences, proposals,etc. here for the presentation

**Comment by felixkittler** [comment]
https://www.dropbox.com/s/jxll9o0zvpmmghg/patternplate_pr%C3%A4si.pdf?dl=0

**Comment by susikaltschmidt** [comment]
Einzelne Elemente in Dateien und Ordnern verschafft Übersicht und man kann es schnell finden. 
Jedoch muss man dafür auch immer viele einzelne Dateien öffnen. 

Für Designer, die noch nicht mit Github und dem Terminal gearbeitet haben, ist der Anfang schwierig, die Entwickler zu unterstützen. 
Mein push hat anfangs nicht geklappt. 

Trotz alledem eine sehr gute und hilfreiche Lernerfahrung für die Zukunft, da ich mich nun viel besser mit dem Git commit/ Terminal auskenne und mehr über die einzelnen Elemente einer Website nachdenke :)
