### ISSUE TITLE
Hover state

### ISSUE THREAD

**Issue by susikaltschmidt** [component-driven-workshop/project-group-five#4]
Like Nicole mentioned before: We haven´t talked about the hover state yet. 
I will post a proposal this afternoon. 
Please feel free to do any suggestions, too ;).

**Comment by susikaltschmidt** [comment]
![desktop hd copy](https://cloud.githubusercontent.com/assets/24250406/21075833/374f67ee-bf1c-11e6-87a5-3041d264e0c4.png)

**Comment by susikaltschmidt** [comment]
General:
Headline color: #40C5B2
Background color: #EDEDED
Stroke color: #979797

Navigation:
Button background color: #919191
Font: Open Sans

Hover State: Bold

**Comment by felixkittler** [comment]
![2016-12-10 22_27_17-unbenannt-1 bei 200 rgb_8 _](https://cloud.githubusercontent.com/assets/18353984/21076287/e03c276a-bf27-11e6-97ba-6af4abddb592.png)

Wie sind die horizontalen Abstände in der Filter-Leiste gedacht?

- Von "All" würde ich schlussfolgern, dass es links und rechts 35px Padding auf den Text gibt, und die einzelnen Buttons dann 25px Abstand haben.
- Allerdings wäre dann "Completed" zu nah an "Active".
- Eine f este Breite je Button funktioniert auch nicht, weil "Completed" dazu insgesamt zu lang ist.

Sollen wir es einfach umbenennen in "Done"?!? ;-)

**Comment by susikaltschmidt** [comment]
In order to avoid letter jumping in hover state: 
- Padding was removed
- Fixed width: 80px

**Comment by felixkittler** [comment]
@susikaltschmidt:
Soweit ich weiß hast du schon Anfang der Woche am Hover State + einigen Design Finetunings gearbeitet.

Gerade jetzt fehlen diese Änderungen aber im Repository.
Kannst du nochmal pushen??!

**Comment by RadioSchattenwelt** [comment]
Ich habe gerade nochmal nachgeschaut, aber kein commit/push von dir da @susikaltschmidt

**Comment by susikaltschmidt** [comment]
ok nach mehreren Konflikten mit dem Terminal, dem Anzeigen des .git Ordners auf dem Mac und dem Github pull/push/passwort usw sind meine Hover Änderungen nun gepusht :)
Vielen Dank an Felix für die Unterstützung 👍 👍
