### ISSUE TITLE
filter logic

### ISSUE THREAD

**Issue by felixkittler** [component-driven-workshop/project-group-five#5]
Hey Leute,

also das Zerstückeln in Atome, und dann das Wieder-Zusammensetzen zur Seite funktioniert soweit ja schon ganz gut. Vielen Dank @Nicole für die viele Vorarbeit!

CSS schaut soweit auch ganz in Ordnung aus, Finetuning fehlt halt noch.

Wo ich leider gar keine Ahnung habe - wie verdrahten wir da jetzt das Javascript?!? Allein der Counter, wie soll das funktionieren? Wenn ich das JS mit in das Atom mit reinschreibe, wird er einen Fehler bringen, weil ich zu der Zeit ja noch gar keine Task-Liste habe (wird im Browser erst nach dem Counter gerendert).

Any hint highly appreciated ;)

**Comment by RadioSchattenwelt** [comment]
So wie ich das verstehe, wird einfach die Zahl von außen mitgegeben. 
Das heisst, du hast ein Element, dass den Counter und die Liste enthält und liest dann die Größe der Liste aus und gibst sie dem Counter.

Das ganze muss dann wohl neu gerendert werden, wenn sich etwas ändert, siehe hier:
https://facebook.github.io/react/docs/rendering-elements.html

**Comment by RadioSchattenwelt** [comment]
Ich denke was wir brauchen, um neu zu rendern ist die setState Methode, siehe hier:
https://facebook.github.io/react/docs/state-and-lifecycle.html

**Comment by felixkittler** [comment]
works like a charm.
thanks @RadioSchattenwelt
